// frontend-angular/src/app/workflow/workflow-canvas/workflow-canvas.ts
import { ChangeDetectionStrategy, Component, computed, effect, signal, viewChild } from '@angular/core';
import { NgIcon, provideIcons } from '@ng-icons/core';
import { lucideMaximize, lucideZoomIn, lucideZoomOut } from '@ng-icons/lucide';
import { ComponentNodeEvent, Connection, Edge, Node, Vflow, VflowComponent, createEdge, createEdges, createNode, createNodes, isComponentNode } from 'ngx-vflow';
import { ContextMenuComponent } from '../context-menu/context-menu';
import { NodePropertiesComponent } from '../node-properties/node-properties';
import { NODE_TEMPLATE_DATA_TRANSFER_TYPE, NodePaletteComponent, isNodeTemplate } from '../node-palette/node-palette';
import { WorkflowNodeComponent, WorkflowNodeData } from '../workflow-node/workflow-node';

function createInitialNodes(): Node[] {
  return createNodes<WorkflowNodeData>([
    { id: '1', point: { x: 250, y: 50 }, type: WorkflowNodeComponent, data: { label: 'Webhook', type: 'trigger', icon: 'webhook', description: 'POST /api/start' } },
    { id: '2', point: { x: 250, y: 200 }, type: WorkflowNodeComponent, data: { label: 'Validate', type: 'condition', icon: 'condition', description: 'Check payload' } },
    { id: '3', point: { x: 150, y: 370 }, type: WorkflowNodeComponent, data: { label: 'Process', type: 'action', icon: 'code', description: 'Transform data' } },
    { id: '4', point: { x: 400, y: 370 }, type: WorkflowNodeComponent, data: { label: 'Error', type: 'output', icon: 'output', description: 'Return 400' } },
    { id: '5', point: { x: 150, y: 530 }, type: WorkflowNodeComponent, data: { label: 'Send Email', type: 'action', icon: 'email', description: 'Notify user' } },
  ]);
}

function createInitialEdges(): Edge[] {
  return createEdges([
    { id: 'e1-2', source: '1', target: '2', curve: 'smooth-step' },
    { id: 'e2-3', source: '2', target: '3', curve: 'smooth-step' },
    { id: 'e2-4', source: '2', sourceHandle: 'false', target: '4', curve: 'smooth-step' },
    { id: 'e3-5', source: '3', target: '5', curve: 'smooth-step' },
  ]);
}

@Component({
  selector: 'app-workflow-canvas',
  standalone: true,
  imports: [Vflow, NgIcon, NodePaletteComponent, NodePropertiesComponent, ContextMenuComponent],
  providers: [provideIcons({ lucideZoomIn, lucideZoomOut, lucideMaximize })],
  templateUrl: './workflow-canvas.html',
  styles: ':host { display: block; width: 100%; height: 100vh; }',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    '(document:keydown)': 'onKeyDown($event)',
  },
})
export class WorkflowCanvasComponent {
  protected readonly nodes = signal<Node[]>(createInitialNodes());
  protected readonly edges = signal<Edge[]>(createInitialEdges());

  protected readonly selectedNode = computed(() => {
    const n = this.nodes().find((x) => x.selected?.());
    return n && isComponentNode<WorkflowNodeData>(n) ? n : undefined;
  });

  protected readonly contextMenu = signal<
    | { type: 'node'; x: number; y: number; nodeId: string }
    | { type: 'canvas'; x: number; y: number; flowPoint: { x: number; y: number } }
    | null
  >(null);

  private readonly vflow = viewChild<VflowComponent>('vflow');

  private hasFitView = false;
  private edgeIdCounter = 0;
  private nodeIdCounter = 0;

  constructor() {
    effect(() => {
      const vflow = this.vflow();
      if (!vflow || this.hasFitView || !vflow.initialized()) return;
      this.hasFitView = true;
      vflow.fitView();
    });
  }

  protected onConnect(connection: Connection): void {
    const exists = this.edges().some(
      (edge) =>
        edge.source === connection.source &&
        edge.target === connection.target &&
        edge.sourceHandle === connection.sourceHandle &&
        edge.targetHandle === connection.targetHandle,
    );
    if (exists) return;

    const id = `e-${connection.source}-${connection.target}-${this.edgeIdCounter++}`;
    const edge = createEdge({ ...connection, id, curve: 'smooth-step' });
    this.edges.update((edges) => [...edges, edge]);
  }

  protected onDragOver(event: DragEvent): void {
    event.preventDefault();
    if (event.dataTransfer) {
      event.dataTransfer.dropEffect = 'move';
    }
  }

  protected onDrop(event: DragEvent): void {
    event.preventDefault();

    const payload = event.dataTransfer?.getData(NODE_TEMPLATE_DATA_TRANSFER_TYPE);
    if (!payload) return;

    let template: unknown;
    try {
      template = JSON.parse(payload);
    } catch {
      return;
    }
    if (!isNodeTemplate(template)) return;

    const vflow = this.vflow();
    if (!vflow) return;

    const point = vflow.documentPointToFlowPoint({ x: event.clientX, y: event.clientY });
    const node = createNode<WorkflowNodeData>({
      id: `node-${this.nodeIdCounter++}`,
      point,
      type: WorkflowNodeComponent,
      data: {
        label: template.label,
        type: template.category,
        icon: template.icon,
        description: template.description,
      },
    });
    this.nodes.update((nodes) => [...nodes, node]);
  }

  protected zoomIn(): void {
    const vflow = this.vflow();
    if (!vflow) return;
    vflow.zoomTo(vflow.viewport().zoom * 1.2);
  }

  protected zoomOut(): void {
    const vflow = this.vflow();
    if (!vflow) return;
    vflow.zoomTo(vflow.viewport().zoom / 1.2);
  }

  protected fitView(): void {
    this.vflow()?.fitView();
  }

  protected onNodeDelete(id: string): void {
    this.nodes.update((nodes) => nodes.filter((node) => node.id !== id));
    this.edges.update((edges) => edges.filter((edge) => edge.source !== id && edge.target !== id));
  }

  protected onNodeDuplicate(id: string): void {
    const source = this.nodes().find((node) => node.id === id);
    if (!source || !isComponentNode<WorkflowNodeData>(source)) return;

    const point = source.point();
    const node = createNode<WorkflowNodeData>({
      id: `node-${this.nodeIdCounter++}`,
      point: { x: point.x + 40, y: point.y + 40 },
      type: WorkflowNodeComponent,
      data: { ...source.data!() },
    });
    this.nodes.update((nodes) => [...nodes, node]);
  }

  protected onComponentNodeEvent(event: ComponentNodeEvent<[WorkflowNodeComponent]>): void {
    if (event.eventName === 'contextMenuRequested') {
      this.contextMenu.set({ type: 'node', x: event.eventPayload.x, y: event.eventPayload.y, nodeId: event.nodeId });
    }
  }

  protected onCanvasContextMenu(event: MouseEvent): void {
    event.preventDefault();

    const vflow = this.vflow();
    if (!vflow) return;

    const flowPoint = vflow.documentPointToFlowPoint({ x: event.clientX, y: event.clientY });
    this.contextMenu.set({ type: 'canvas', x: event.clientX, y: event.clientY, flowPoint });
  }

  protected onAddNodeFromMenu(category: 'trigger' | 'action' | 'condition' | 'output', point: { x: number; y: number }): void {
    const defaults: Record<'trigger' | 'action' | 'condition' | 'output', { label: string; icon: string; description: string }> = {
      trigger: { label: 'New Trigger', icon: 'trigger', description: 'Configure trigger' },
      action: { label: 'New Action', icon: 'action', description: 'Configure action' },
      condition: { label: 'If / Else', icon: 'condition', description: 'Add condition' },
      output: { label: 'Response', icon: 'output', description: 'Return result' },
    };
    const d = defaults[category];
    const node = createNode<WorkflowNodeData>({
      id: `node-${this.nodeIdCounter++}`,
      point,
      type: WorkflowNodeComponent,
      data: { label: d.label, type: category, icon: d.icon, description: d.description },
    });
    this.nodes.update((nodes) => [...nodes, node]);
  }

  protected onKeyDown(event: KeyboardEvent): void {
    if (event.key !== 'Delete' && event.key !== 'Backspace') return;

    const target = event.target as HTMLElement | null;
    if (target?.closest('input, textarea, button, [contenteditable="true"], [role="switch"], [role="listbox"], [role="option"]')) return;

    const deletedNodeIds = new Set(this.nodes().filter((node) => node.selected?.()).map((node) => node.id));
    const hasSelectedEdge = this.edges().some((edge) => edge.selected?.());
    if (deletedNodeIds.size === 0 && !hasSelectedEdge) return;

    event.preventDefault();
    this.nodes.update((nodes) => nodes.filter((node) => !node.selected?.()));
    this.edges.update((edges) =>
      edges.filter(
        (edge) =>
          !edge.selected?.() && !deletedNodeIds.has(edge.source) && !deletedNodeIds.has(edge.target),
      ),
    );

    const menu = this.contextMenu();
    if (menu && menu.type === 'node' && deletedNodeIds.has(menu.nodeId)) {
      this.contextMenu.set(null);
    }
  }
}

// frontend/src/components/workflow/WorkflowCanvas.tsx
import { useCallback, useRef, useState } from 'react';
import ReactFlow, {
  addEdge,
  Background,
  Controls,
  MiniMap,
  useNodesState,
  useEdgesState,
  Connection,
  ReactFlowProvider,
  ReactFlowInstance,
  BackgroundVariant,
  MarkerType,
  Node,
  NodeMouseHandler,
  Edge,
} from 'reactflow';
import 'reactflow/dist/style.css';
import WorkflowNode from './WorkflowNode';
import NodeProperties from './NodeProperties';
import ContextMenu from './ContextMenu';

const nodeTypes = { workflowNode: WorkflowNode };

const defaultNodes: Node[] = [
  { id: '1', type: 'workflowNode', position: { x: 250, y: 50 }, data: { label: 'Webhook', type: 'trigger', icon: 'webhook', description: 'POST /api/start' } },
  { id: '2', type: 'workflowNode', position: { x: 250, y: 200 }, data: { label: 'Validate', type: 'condition', icon: 'condition', description: 'Check payload' } },
  { id: '3', type: 'workflowNode', position: { x: 150, y: 370 }, data: { label: 'Process', type: 'action', icon: 'code', description: 'Transform data' } },
  { id: '4', type: 'workflowNode', position: { x: 400, y: 370 }, data: { label: 'Error', type: 'output', icon: 'output', description: 'Return 400' } },
  { id: '5', type: 'workflowNode', position: { x: 150, y: 530 }, data: { label: 'Send Email', type: 'action', icon: 'email', description: 'Notify user' } },
];

const defaultEdges: Edge[] = [
  { id: 'e1-2', source: '1', target: '2', markerEnd: { type: MarkerType.ArrowClosed, width: 16, height: 16 }, animated: true },
  { id: 'e2-3', source: '2', target: '3', markerEnd: { type: MarkerType.ArrowClosed, width: 16, height: 16 } },
  { id: 'e2-4', source: '2', sourceHandle: 'false', target: '4', markerEnd: { type: MarkerType.ArrowClosed, width: 16, height: 16 }, style: { strokeDasharray: '5 5' } },
  { id: 'e3-5', source: '3', target: '5', markerEnd: { type: MarkerType.ArrowClosed, width: 16, height: 16 } },
];

let nodeId = 10;

type ContextMenuState = {
  x: number;
  y: number;
  type: 'node' | 'canvas' | 'edge';
  nodeId?: string;
  edgeId?: string;
  flowPosition?: { x: number; y: number };
} | null;

interface WorkflowCanvasInnerProps {
  initialNodes?: Node[];
  initialEdges?: Edge[];
  getStateRef: React.MutableRefObject<(() => { nodes: Node[]; edges: Edge[] }) | null>;
}

const WorkflowCanvasInner = ({ initialNodes, initialEdges, getStateRef }: WorkflowCanvasInnerProps) => {
  const reactFlowWrapper = useRef<HTMLDivElement>(null);
  const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes || defaultNodes);
  const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges || defaultEdges);
  const [rfInstance, setRfInstance] = useState<ReactFlowInstance | null>(null);
  const [selectedNode, setSelectedNode] = useState<Node | null>(null);
  const [contextMenu, setContextMenu] = useState<ContextMenuState>(null);

  // Expose current state to parent
  getStateRef.current = () => ({ nodes, edges });

  const onConnect = useCallback(
    (params: Connection) =>
      setEdges((eds) =>
        addEdge({ ...params, markerEnd: { type: MarkerType.ArrowClosed, width: 16, height: 16 } }, eds)
      ),
    [setEdges]
  );

  const onNodeClick: NodeMouseHandler = useCallback((_event, node) => {
    setSelectedNode(node);
    setContextMenu(null);
  }, []);

  const onPaneClick = useCallback(() => {
    setSelectedNode(null);
    setContextMenu(null);
  }, []);

  const deleteNode = useCallback((id: string) => {
    setNodes((nds) => nds.filter((n) => n.id !== id));
    setEdges((eds) => eds.filter((e) => e.source !== id && e.target !== id));
    setSelectedNode((prev) => (prev?.id === id ? null : prev));
  }, [setNodes, setEdges]);

  const duplicateNode = useCallback((id: string) => {
    const node = nodes.find((n) => n.id === id);
    if (!node) return;
    const newNode: Node = {
      id: `node-${nodeId++}`,
      type: 'workflowNode',
      position: { x: node.position.x + 40, y: node.position.y + 40 },
      data: { ...node.data },
    };
    setNodes((nds) => [...nds, newNode]);
  }, [nodes, setNodes]);

  const deleteEdge = useCallback((id: string) => {
    setEdges((eds) => eds.filter((e) => e.id !== id));
  }, [setEdges]);

  const addNodeAtPosition = useCallback((category: string, position: { x: number; y: number }) => {
    const defaults: Record<string, { label: string; icon: string; description: string }> = {
      trigger: { label: 'New Trigger', icon: 'trigger', description: 'Configure trigger' },
      action: { label: 'New Action', icon: 'action', description: 'Configure action' },
      condition: { label: 'If / Else', icon: 'condition', description: 'Add condition' },
      output: { label: 'Response', icon: 'output', description: 'Return result' },
    };
    const d = defaults[category] || defaults.action;
    const newNode: Node = {
      id: `node-${nodeId++}`,
      type: 'workflowNode',
      position,
      data: { label: d.label, type: category, icon: d.icon, description: d.description },
    };
    setNodes((nds) => [...nds, newNode]);
  }, [setNodes]);

  const onNodeContextMenu = useCallback((event: React.MouseEvent, node: Node) => {
    event.preventDefault();
    setContextMenu({ x: event.clientX, y: event.clientY, type: 'node', nodeId: node.id });
  }, []);

  const onEdgeContextMenu = useCallback((event: React.MouseEvent, edge: Edge) => {
    event.preventDefault();
    setContextMenu({ x: event.clientX, y: event.clientY, type: 'edge', edgeId: edge.id });
  }, []);

  const onPaneContextMenu = useCallback((event: React.MouseEvent) => {
    event.preventDefault();
    if (!rfInstance || !reactFlowWrapper.current) return;
    const bounds = reactFlowWrapper.current.getBoundingClientRect();
    const flowPosition = rfInstance.project({
      x: event.clientX - bounds.left,
      y: event.clientY - bounds.top,
    });
    setContextMenu({ x: event.clientX, y: event.clientY, type: 'canvas', flowPosition });
  }, [rfInstance]);

  const onNodeDataUpdate = useCallback((id: string, data: Record<string, any>) => {
    setNodes((nds) => nds.map((n) => (n.id === id ? { ...n, data } : n)));
    setSelectedNode((prev) => (prev && prev.id === id ? { ...prev, data } : prev));
  }, [setNodes]);

  const onDragOver = useCallback((event: React.DragEvent) => {
    event.preventDefault();
    event.dataTransfer.dropEffect = 'move';
  }, []);

  const onDrop = useCallback(
    (event: React.DragEvent) => {
      event.preventDefault();
      const data = event.dataTransfer.getData('application/reactflow');
      if (!data || !rfInstance || !reactFlowWrapper.current) return;
      const template = JSON.parse(data);
      const bounds = reactFlowWrapper.current.getBoundingClientRect();
      const position = rfInstance.project({ x: event.clientX - bounds.left, y: event.clientY - bounds.top });
      const newNode: Node = {
        id: `node-${nodeId++}`,
        type: 'workflowNode',
        position,
        data: { label: template.label, type: template.category, icon: template.icon, description: template.description },
      };
      setNodes((nds) => [...nds, newNode]);
    },
    [rfInstance, setNodes]
  );

  const currentSelectedNode = selectedNode ? nodes.find((n) => n.id === selectedNode.id) || null : null;

  return (
    <div className="flex flex-1 overflow-hidden">
      <div ref={reactFlowWrapper} className="flex-1 h-full">
        <ReactFlow
          nodes={nodes}
          edges={edges}
          onNodesChange={onNodesChange}
          onEdgesChange={onEdgesChange}
          onConnect={onConnect}
          onInit={setRfInstance}
          onDragOver={onDragOver}
          onDrop={onDrop}
          onNodeClick={onNodeClick}
          onPaneClick={onPaneClick}
          onNodeContextMenu={onNodeContextMenu}
          onEdgeContextMenu={onEdgeContextMenu}
          onPaneContextMenu={onPaneContextMenu}
          nodeTypes={nodeTypes}
          fitView
          deleteKeyCode={['Backspace', 'Delete']}
          snapToGrid
          snapGrid={[16, 16]}
          defaultEdgeOptions={{ type: 'smoothstep', style: { strokeWidth: 2 } }}
        >
          <Background variant={BackgroundVariant.Dots} gap={20} size={1} color="hsl(var(--canvas-grid))" />
          <Controls />
          <MiniMap nodeColor={() => 'hsl(var(--primary))'} maskColor="hsl(var(--background) / 0.8)" style={{ borderRadius: 8 }} />
        </ReactFlow>
      </div>
      {currentSelectedNode && (
        <NodeProperties
          node={currentSelectedNode}
          onUpdate={onNodeDataUpdate}
          onClose={() => setSelectedNode(null)}
          onDelete={deleteNode}
        />
      )}
      {contextMenu && (
        <ContextMenu
          x={contextMenu.x}
          y={contextMenu.y}
          type={contextMenu.type}
          onClose={() => setContextMenu(null)}
          onDeleteNode={contextMenu.nodeId ? () => { deleteNode(contextMenu.nodeId!); setContextMenu(null); } : undefined}
          onDuplicateNode={contextMenu.nodeId ? () => { duplicateNode(contextMenu.nodeId!); setContextMenu(null); } : undefined}
          onDeleteEdge={contextMenu.edgeId ? () => { deleteEdge(contextMenu.edgeId!); setContextMenu(null); } : undefined}
          onAddNode={contextMenu.flowPosition ? (category: string) => { addNodeAtPosition(category, contextMenu.flowPosition!); setContextMenu(null); } : undefined}
        />
      )}
    </div>
  );
};

interface WorkflowCanvasProps {
  initialNodes?: Node[];
  initialEdges?: Edge[];
  getStateRef: React.MutableRefObject<(() => { nodes: Node[]; edges: Edge[] }) | null>;
}

const WorkflowCanvas = ({ initialNodes, initialEdges, getStateRef }: WorkflowCanvasProps) => (
  <ReactFlowProvider>
    <WorkflowCanvasInner initialNodes={initialNodes} initialEdges={initialEdges} getStateRef={getStateRef} />
  </ReactFlowProvider>
);

export default WorkflowCanvas;
